### ISSUE TITLE
How do you retrieve the csrf_token 

### ISSUE THREAD

**Issue by Ces-D** [Bogpan/spotify-rs#10]
How do you avoid the `InvalidStateParameter` error caused when calling `client.authenticate`. The token is generated [randomly](https://github.com/Bogpan/spotify-rs/blob/main/src/client.rs#L161) so I am unable to match the error [here](https://github.com/Bogpan/spotify-rs/blob/main/src/client.rs#L989). Am I missing something?

**Comment by Bogpan** [comment]
Could you provide an example? Also, are you on the latest version? Whitespace wouldn't be trimmed as pointed out in #7, but that was fixed.

**Comment by Bogpan** [comment]
I re-read your post and as a clarification, take a look at the [README](https://github.com/Bogpan/spotify-rs/blob/main/README.md) and [here](https://developer.spotify.com/documentation/web-api/tutorials/code-pkce-flow).

The way it works is when you createa  new client, you get back a `(client, url)`. You must redirect the user to said URL, they must authorise their account, then the user will be redirected to something like `[your redirect_url]?code=abc&state=def`
From there you can get the code and state which you need to pass to `client.authenticate`.

**Comment by Ces-D** [comment]
ah, thank you. yes that clarifies it.
