### ISSUE TITLE
Functional Pagination

### ISSUE THREAD

**Issue by Multimodcrafter** [Bogpan/spotify-rs#2]
Hi, I'm currently using your API bindings to implement a project and am very happy for your work.

One thing that bothers me though: when querying things that require pagination, you return the beautiful `Page<>` struct, but you don't offer any methods for conveniently fetching the next/previous page (or at least I couldn't figure out how). This means an index calculation based of the information in the response is required, followed by a whole more run through the builder setup.

I would like to offer my help in implementing this functionality if you are interested :)

**Comment by Bogpan** [comment]
Hey, thanks! I'm happy to hear you like the project!

Yes, pagination has always been a thought and is something I've wanted and still want to implement, I just hadn't found the right moment (I haven't coded at all in a few months, school is keeping me pretty busy). There are LOTS of features I have in mind for this project and I would like to implement all of them at some point, but I'm not even sure I'm satisfied with the builder API, which has been through a few MAJOR rewrites. For now I'm sticking with it for lack of a better alternative, but it's something I may want to change in the future.

Anyway, I'm definitely interested in adding support for pagination, I'll hopefully start working on it soon, and any help is welcome!

**Comment by Bogpan** [comment]
Hey! I recently published the `next` branch (which will see breaking changes), but that means I can implement pagination now in next.

Thanks for the PR, good stuff! I've taken a look at your pagination branch, from which I took inspiration and my implementation is virtually the same, with a new `Error::NoRemainingPages` variant added and a bit of error handling done.

Another difference is the `get_all` method, that gets the previous pages too. There's `get_remaining` to get only the pages after the current one.

I'll add pagination for `CursorPage` too next. I'm wondering if there's any change you'd suggest or issue you see?

**Comment by Bogpan** [comment]
Pagination is completely done on the [`next`](https://github.com/Bogpan/spotify-rs/tree/next) branch.

**Comment by Multimodcrafter** [comment]
Hello :)
Sorry for the late reply; life was very busy lately.

I took a look at the current state of the next branch and it looks good to me what you have so far.
One minor detail: your `get_all` method returns the items in a different order than if one took the first page and called `get_remaining` because you first append the items of the previous pages in reverse order. This might confuse a user. I don't think it needs to be changed necessarily, but if you leave it this way, I would certainly document it.

Also, it would most likely be useful to have a `get_all` / `get_remaining` function for the cursor page as well (not sure whether that is still a todo for you or you didn't consider it), but that's more of a nice to have since it is easily possible to implement it by oneself with the provided `before` and `after` methods.
